config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  devise_scope :user do
    authenticated  do
      root to: 'users#show'
    end

    unauthenticated do
      root to: 'pages#home', as: 'unauthenticated_root'
    end
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: [:show] do
    resources :addresses, only: %i[index new create edit update destroy] do
      post :create_from_coordinates, on: :collection
      patch :update_from_participants, on: :collection
    end
  end

  resources :events, only: %i[show new create] do
    resources :participants, only: %i[new create]
    resources :votes, only: %i[new create]
  end
  resources :participants, only: %i[destroy]
  resources :restaurants, only: %i[index show new create]
  resources :selected_restaurants, only: %i[create]

end

app/models/participant.rb
class Participant < ApplicationRecord
  belongs_to :event
  belongs_to :user
  belongs_to :address
  has_many :votes, dependent: :destroy
end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController
  def new
    @event = Event.find(params[:event_id])

    @markers = []
    @event.participants.each do |participant|
      if participant.user.profile_picture.attached?
        icon = { url: ActionController::Base.helpers.cl_image_path(participant.user.profile_picture.key, transformation: [{radius: 'max'}]), scaledSize: { width: 50, height: 50} }
      else
        icon = { url: (participant.user.facebook_picture_url || "http://placehold.it/50x50"), scaledSize: { width: 50, height: 50} }
      end
      coordinates = []
      coordinates << participant.address.latitude.to_f
      coordinates << participant.address.longitude.to_f
      @markers = @markers << { lat: coordinates[0], lng: coordinates[1], icon: icon, infoWindow: { content: render_to_string(partial: "/participants/infowindow_address", locals: { participant: participant }) } }
    end

    if params[:query].present?
      sql_query = "first_name ILIKE :query OR last_name ILIKE :query"
      @users = User.where(sql_query, query: "%#{params[:query]}%")
    else
      @users = User.all
    end
  end

  def create
    @participant = Participant.new(event_id: params[:event_id], user_id: params[:user])
    @participant.address = @participant.user.addresses.find_by(active: true)
    @participant.save
    redirect_to new_event_participant_path(:anchor => "anchor")
  end

  def destroy
    @participant = Participant.find(params[:id])
    @event = @participant.event
    @participant.destroy
    redirect_to new_event_participant_path(@event, :anchor => "anchor")
  end

end

app/views/participants/_infowindow.html.erb
<div class="infowindow ">
  <div style="text-align: center"><h5>Transit 🚇</h5></div>
  <div style="display: flex; justify-content: space-between; font-size: 16px;">
    <p>⏱️<%= @directions[participant][:transit_duration] %>   </p>
    <p>📍<%= @directions[participant][:transit_distance] %></p>
  </div>
</div>

app/views/participants/_infowindow_address.html.erb
<div class="infowindow ">
  <div class="infowindow-address">
    <% participant.user.addresses.each do |address| %>
          <%= link_to "#{address.name}", update_from_participants_user_addresses_path(participant.user, address: address, event: participant.event, participant: participant), method: :patch, remote: true, id: participant.address == address ? "active" : "inactive" %>
    <% end %>
  </div>
</div>

app/views/participants/new.html.erb
<div style="height: 100vh;">
  <%= render 'shared/navbar' %>
  <div class="map-div d-flex justify-content-center">
    <div id="map" data-markers="<%= @markers.to_json %>" style="width: 100%;
      height: 80vh;"></div>
  </div>

  <div class="bottom-div">
    <div class="btn-middle search-friend">
      <%= form_tag new_event_participant_path(@event), method: :get do %>
      <div class="d-flex justify-content-center">
        <%= text_field_tag :query,
          params[:query],
          class: "form-control",
            id:"search-query",
          placeholder: "Search for a friend"
        %>
      <% end %>
      </div>
    </div>
    <div>
      <div id="anchor"></div>
      <div class="friend-cards pt-6">
        <% @users.each do |user| %>
          <% unless user.addresses.empty? %>
            <div class="card-avatar-add">
              <% if user.profile_picture.attached? %>
                <%= cl_image_tag user.profile_picture.key, class: "avatar" %>
              <% elsif user.facebook_picture_url %>
                <%= image_tag user.facebook_picture_url, class: "avatar" %>
              <% else %>
                <i class="card-no-avatar far fa-user"></i>
              <% end %>
              <p class="avatar-name">
                <%= user.first_name %>
              </p>
              <% participant = Participant.find_by(user: user, event: @event) %>
              <% if participant %>
                <%= link_to participant_path(participant), method: :delete, class: "add-button" do %>
                  <i class="fas fa-minus-circle btn-create"></i>
                <% end %>
              <% else  %>
                <%= link_to event_participants_path(@event, user: user.id), method: :post, class: "add-button" do %>
                  <i class="fas fa-plus-circle btn-create"></i>
                <% end %>
              <% end %>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
        <%= link_to "Let's Go!", restaurants_path(event: @event), class: "btn btn-lesconvives", id:"loader" %>
  </div>

</div>

<img src="https://media.giphy.com/media/RKpEx82Qv99Ddw31GJ/giphy.gif" alt="loader" class="loader-gif">