config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  devise_scope :user do
    authenticated  do
      root to: 'users#show'
    end

    unauthenticated do
      root to: 'pages#home', as: 'unauthenticated_root'
    end
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: [:show] do
    resources :addresses, only: %i[index new create edit update destroy] do
      post :create_from_coordinates, on: :collection
      patch :update_from_participants, on: :collection
    end
  end

  resources :events, only: %i[show new create] do
    resources :participants, only: %i[new create]
    resources :votes, only: %i[new create]
  end
  resources :participants, only: %i[destroy]
  resources :restaurants, only: %i[index show new create]
  resources :selected_restaurants, only: %i[create]

end

app/models/user.rb
class User < ApplicationRecord
  has_many :addresses, dependent: :destroy
  has_many :participants
  has_many :events, through: :participants
  has_one_attached :profile_picture
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:facebook]

  def self.find_for_facebook_oauth(auth)
      user_params = auth.slice("provider", "uid")
      user_params.merge! auth.info.slice("email", "first_name", "last_name")
      user_params[:facebook_picture_url] = auth.info.image
      user_params[:token] = auth.credentials.token
      user_params[:token_expiry] = Time.at(auth.credentials.expires_at)
      user_params = user_params.to_h

      user = User.find_by(provider: auth.provider, uid: auth.uid)
      user ||= User.find_by(email: auth.info.email) # User did a regular sign up in the past.
      if user
        user.update(user_params)
      else
        user = User.new(user_params)
        user.password = Devise.friendly_token[0,20]  # Fake password for validation
        user.save
      end

      return user
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    user = User.find_for_facebook_oauth(request.env['omniauth.auth'])

    if user.persisted?
      sign_in_and_redirect user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
    @facebook_photo = current_user.facebook_picture_url
    @event = Event.new()
  end
end

app/views/users/show.html.erb
<%= render 'shared/navbar' %>

<div class="d-flex flex-column user-show">

<!-- top div -->
  <div class=" top-div-user d-flex flex-column justify-content-center align-items-center">
    <div>
      <% if current_user.profile_picture.attached? %>
        <%= cl_image_tag (current_user.profile_picture.key), height: 120, width: 120, crop: :fill, class: "user-show-avatar" %>
      <% elsif @facebook_photo %>
        <%= image_tag @facebook_photo, alt: "Picture of #{@user.first_name}", width: 100, height: 100 %>
      <% else %>
        <i class="card-no-avatar far fa-user"></i>
        <% end %>
      </div>

      <p class="welcome-message"><%= "Hello #{@user.first_name}!" %></p>
      <div id="user-address">
        <% if @user.addresses.find_by(active: true) %>
          <%= link_to user_addresses_path(@user) do %>
            <%= @user.addresses.find_by(active: true).full_address %>
<!--             <i class="far fa-edit"></i> -->
          <% end %>
        <% elsif @user.addresses.first %>
          <%= link_to user_addresses_path(@user) do %>
            <%= @user.addresses.first.full_address %>
<!--             <i class="far fa-edit"></i> -->
          <% end %>
        <% else %>
          <%= link_to new_user_address_path(@user) do %>
            <p> Add an address <i class="fas fa-location-arrow"></i> </p>
          <% end %>
        <% end %>
      </div>
    </div>

<!-- other div -->
  <% if @user.addresses.first %>
    <div class="bottom-div">
      <div class="btn-middle">
        <button type="button" class="btn-lesconvives" data-toggle="modal" data-target="#exampleModalCenter">
          My new event
          <i class="fas fa-plus-circle"></i>
        </button>
      </div>
    </div>

<!-- third div -->

      <div class="container-user-profile">
        <% current_user.events.order(:date).reverse_order.each do |event| %>
          <% unless event.selected_restaurants.empty? %>
            <div class="card-product">
              <div class="card-image-and-date" style="position: relative;">
                <%= cl_image_tag event.selected_restaurants.first.restaurant.photo.key, class: "card-illustration" %>
                <p id="event-date"> <%= event.date.strftime("%d %^b") %></p>
              </div>
              <div class="card-product-infos">
                <h2> <%= event.name %></h2>
                  <div class="d-flex flex-row">
                    <% event.users.each do |user| %>
                      <div class="mr-2">
                        <% if user.profile_picture.attached? %>
                          <%= cl_image_tag user.profile_picture.key, class: "avatar" %>
                        <% elsif user.facebook_picture_url %>
                          <%= image_tag user.facebook_picture_url, class: "avatar" %>
                        <% else %>
                          <i class="card-no-avatar far fa-user"></i>
                        <% end %>
                      </div>
                    <% end %>
                  </div>
              </div>
            </div>
          <% end %>
        <% end %>
    </div>
  </div>
</div>
<% end %>

<!-- Modal -->
<div class="modal fade <%= 'show' if params["controller"] == 'events' %>"
  style="display: <%= 'block' if params["controller"] == 'events' %>;"
  id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle"
  aria-hidden="<%= 'true' if params["controller"] == 'events' %>"
  aria-modal=" <%'true' if params["controller"] == 'events' %>" >

  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
<!--       <div class="modal-header"> -->
<!--         <h3 class="modal-title" id="exampleModalCenterTitle">Create a new event</h3> -->
<!--         <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div> -->
      <%= simple_form_for(@event) do |f| %>
        <div class="modal-body">
            <%= f.input :name, label: "Give it a Name!" %>
            <div class="d-flex justify-content-between">
              <%= f.input :date, as: :string, input_html: {class: "datepicker"}, label: "When is it happening?"%>
              <%= f.input :hour, as: :string, input_html: {class: "hourpicker"}, label: "At what time?" %>
            </div>
        </div>
        <div class="modal-footer">
        <%= f.submit class: "btn-lesconvives" %>
        </div>
      <% end %>
    </div>
  </div>
</div>
<% if params["controller"] == 'events' %>
  <div class="modal-backdrop fade show"></div>
<% end %>