config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  devise_scope :user do
    authenticated  do
      root to: 'users#show'
    end

    unauthenticated do
      root to: 'pages#home', as: 'unauthenticated_root'
    end
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: [:show] do
    resources :addresses, only: %i[index new create edit update destroy] do
      post :create_from_coordinates, on: :collection
      patch :update_from_participants, on: :collection
    end
  end

  resources :events, only: %i[show new create] do
    resources :participants, only: %i[new create]
    resources :votes, only: %i[new create]
  end
  resources :participants, only: %i[destroy]
  resources :restaurants, only: %i[index show new create]
  resources :selected_restaurants, only: %i[create]

end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :selected_restaurants
  has_many :events, through: :selected_restaurants
  validates :name, presence: true
  has_one_attached :photo
  geocoded_by :address
  reverse_geocoded_by :latitude, :longitude
  after_validation :geocode, :reverse_geocode, if: :will_save_change_to_address?
  CATEGORY = %w[American Chinese French Greek Indian Italian Japanese Korean Lebanese Mexican Spanish Thai]
  RATINGS = [ 1, 2, 3, 4, 5 ]
  PRICE_LEVEL = [ 1, 2, 3, 4, 5 ]
end

app/controllers/restaurants_controller.rb
require 'json'
require 'open-uri'

class RestaurantsController < ApplicationController

  def index
    if params[:food_category].present?
      food_category = params[:food_category]
    else
      food_category = ""
    end
    @geographic_center = geo_center_to_address(geographic_center)
    @directions = directions_to_geographic_center_distance_matrix_api
    @lat = geographic_center[0]
    @lng = geographic_center[1]

# si pas de params ou si params food category
    if params[:food_category].present? || Restaurant.near(geographic_center, 0.1).empty?
      @results_restaurants = parse_google_api(@lat, @lng, food_category)
      @details_restaurants = parse_restaurant_details_api(@results_restaurants)
      if params[:rating].present?
        @results_restaurants = @results_restaurants.select {|r| r.rating == params[:rating].to_i}
      end
      if params[:price_level].present?
        @results_restaurants = @results_restaurants.select {|r| r.price_level == params[:price_level].to_i}
      end
    else

      @results_restaurants = Restaurant.near(geographic_center, 0.1).limit(20)
      if params[:rating].present?
        @results_restaurants = @results_restaurants.where(rating: params[:rating])
      end
      if params[:price_level].present?
        @results_restaurants = @results_restaurants.where(price_level: params[:price_level])
      end
    end
    @markers = @results_restaurants.select {|r| r.latitude.present? && r.longitude.present? && r.photo.present? }.map do |restaurant|
        {
        lat: restaurant.latitude,
        lng: restaurant.longitude,
        details: {
          id: restaurant.id,
          name: restaurant.name,
          rating: restaurant.rating,
          short_address: restaurant.short_address,
          photo_key: restaurant.photo.key,
          price_level: restaurant.price_level.to_i,
          event: params[:event],
          # food_category: restaurant.food_category
        },
        icon: ActionController::Base.helpers.asset_url('resto_marker.png')
        #infoWindow: { content: render_to_string(partial: "/restaurants/infowindow", locals: { restaurant: restaurant }) }
      }
    end
# markers for geocenter
    @markers = @markers << { lat: @lat, lng: @lng, icon: ActionController::Base.helpers.asset_url('center.png'), infoWindow: { content: render_to_string(partial: "/restaurants/infowindowcenter", locals: { center: @shortened_address }) } }

# markers for each participant
    @participants.each do |participant|
      coordinates = []
      coordinates << participant.address.latitude.to_f
      coordinates << participant.address.longitude.to_f
      if participant.user.profile_picture.attached?
        icon = { url: ActionController::Base.helpers.cl_image_path(participant.user.profile_picture.key, transformation: [{radius: 'max'}]), scaledSize: { width: 50, height: 50, borderRadius: '50px'} }
      else
        icon = { url: (participant.user.facebook_picture_url || "http://placehold.it/30x30"), scaledSize: { width: 50, height: 50, borderRadius: '50px'} }
      end
      @markers = @markers << { lat: coordinates[0], lng: coordinates[1], icon: icon }
    end
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @event = Event.find(params[:event])
  end

  private

  def parse_google_api(lat, lng, food_category)
    url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json?keyword=#{food_category}&location=#{lat},#{lng}&radius=200&type=restaurant&key=#{ENV["GOOGLE_MAPS_TOKEN"]}"
    restaurants_serialized = open(url).read
    restaurants = JSON.parse(restaurants_serialized)["results"]
    final_restaurants = restaurants.map do |restaurant|
      resto = Restaurant.find_or_create_by(google_api_id: restaurant["id"]) do |r|
        r.name = restaurant["name"]
        r.price_level = restaurant["price_level"]
        r.rating = restaurant["rating"]
        r.address = restaurant["vicinity"]
        r.short_address = restaurant["vicinity"]
        r.google_api_id = restaurant["id"]
        r.place_id_google = restaurant["place_id"]
      end
      if restaurant["photos"] && !resto.photo.attached?
        res = Net::HTTP.get_response(URI("https://maps.googleapis.com/maps/api/place/photo?key=#{ENV["GOOGLE_MAPS_TOKEN"]}&photoreference=#{restaurant["photos"][0]["photo_reference"]}&maxwidth=400"))
        file = URI.open(res['location'])
        resto.photo.attach(io: file, filename: "#{restaurant["id"]}.jpg", content_type: 'image/jpg')
      end

      if food_category != ""
        resto.food_category = "#{food_category}"
      end
      resto.save!
      resto
    end
    return final_restaurants
  end

  def parse_restaurant_details_api(final_restaurants)
    @restaurants = final_restaurants
    @restaurants.each do |restaurant|
      url = "https://maps.googleapis.com/maps/api/place/details/json?place_id=#{restaurant.place_id_google}&key=#{ENV["GOOGLE_MAPS_TOKEN"]}"
      restaurants_serialized = open(url).read
      restaurants = JSON.parse(restaurants_serialized)["result"]
      if restaurants != nil
        resto = Restaurant.find_or_create_by(google_api_id: restaurants["id"])
        resto.opening_hours = restaurants["opening_hours"]["weekday_text"] if restaurants["opening_hours"]
        resto.url = restaurants["website"]
        resto.phone = restaurants["formatted_phone_number"]
        resto.save!
        resto
      end
    end
    return @restaurants
  end

  def geographic_center
    # retrive_participants_geo_positions
    @event = Event.find(params[:event])
    @geo_positions = []
    @participants = @event.participants
    @participants.each do |participant|
      coordinates = []
      coordinates << participant.address.latitude.to_f
      coordinates << participant.address.longitude.to_f
      @geo_positions << coordinates
    end
    # find_geographic_center
    geographic_center = Geocoder::Calculations.geographic_center(@geo_positions)
  end

  def geo_center_to_address(geo_center)
    results = Geocoder.search([geo_center[0], geo_center[1]])
    if results.any?
      @full_address = results.first.data['address']
      if @full_address['road'].nil?
        road = @full_address['way']
      else
        road = @full_address['road']
      end
      @shortened_address = "#{road}, #{@full_address['postcode']}, #{@full_address['city']}"
    end
    return @shortened_address
  end

  # def directions_to_geographic_center_directions_api
  #   @participants = Participant.all
  #   @participants.each do |participant|
  #     url = "https://maps.googleapis.com/maps/api/directions/json?&origin=#{participant.address.latitude.to_f},#{participant.address.longitude.to_f}&destination=#{geographic_center[0]},#{geographic_center[1]}&mode=transit&key=#{ENV["GOOGLE_MAPS_TOKEN"]}"
  #     directions_serialized = open(url).read
  #     directions = JSON.parse(directions_serialized)
  #   end
  # end

  def directions_to_geographic_center_distance_matrix_api
    @event = Event.find(params[:event])
    @participants = @event.participants
    directions = {}
    @participants.each do |participant|
      url = "https://maps.googleapis.com/maps/api/distancematrix/json?units=metric&origins=#{participant.address.latitude},#{participant.address.longitude}&destinations=#{geographic_center[0]},#{geographic_center[1]}&mode=transit&key=#{ENV["GOOGLE_MAPS_TOKEN"]}"
      directions_serialized = open(url).read
      parsed_directions = JSON.parse(directions_serialized)
      transit_duration = parsed_directions['rows'].first['elements'].first['duration']['text']
      transit_distance = parsed_directions['rows'].first['elements'].first['distance']['text']
      directions[participant] = {
        transit_duration: transit_duration,
        transit_distance: transit_distance
      }
    end
    return directions
  end
end

app/views/restaurants/_infowindow.html.erb
<div class="infowindow infowindow-resto">
  <div style="text-align: center">
    <h5>🍴<%= restaurant.name %></h5>
    <div style="display: flex; justify-content: space-around; font-size: 16px;">
      <p >⭐<bold><%= restaurant.rating %>/5</bold></p>
      <p><bold><%= "€"*restaurant.price_level.to_i %></bold></p>
    </div>
    <div class="view-card-btn">
      <%= link_to "VIEW", restaurant_path(restaurant[:id], event: params[:event]), class: "view-card-btn-link" %>
    </div>
  </div>
</div>

app/views/restaurants/_infowindowcenter.html.erb
<div class="infowindow ">
  <div style="text-align: center">
      <p>📍<%= @shortened_address %> </p>
  </div>
</div>

app/views/restaurants/index.html.erb
<%= render 'shared/navbar' %>

<div class="map-div">
  <div id="map" data-markers="<%= @markers.to_json %>" style="width: 100%;
    height: 80vh;"></div>
</div>


<div class="resto-cards">
  <a class="link-show-resto">
    <div class="card-resto">
      <img class="resto-img" alt="photo restaurant" src="">
      <div class="card-resto-infos">
        <div class="resto-header">
          <h2 class="resto-name"> </h2>
          <h2 class="card-trip-pricing"></h2>
        </div>
        <div>
          <p class="resto-rating"></p>
          <p class="resto-short-address"></p>
        </div>
      </div>
    </div>

  </a>
</div>

<div class="align-button">
  <div class="fixed-filter">
    <button type="button" class="btn-filter" data-toggle="modal" data-target="#exampleModalCenter">
      <i class="fas fa-filter"></i>
    </button>
  </div>
  <div id="meetpoint">
    <p class="meeting-point" >📍 <%= @geographic_center %></p>
  </div>
</div>

<div class="container">
  <% @participants.each do |participant| %>
      <p>
      <% if participant.user.profile_picture.attached? %>
        <%= cl_image_tag participant.user.profile_picture.key, class: "avatar transit-time" %>
      <% else %>
        <%= participant.user.facebook_picture_url || "http://placehold.it/30x30"%>
      <%end %>
       ⏱️<%= @directions[participant][:transit_duration] %>
       📍<%= @directions[participant][:transit_distance] %>
      </p>
      <hr>
  <% end %>
</div>


<!-- Modal filtre -->
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <div>
          <%= form_tag restaurants_path, method: :get do %>
            <% food_category = Restaurant::CATEGORY %>
            <fieldset class="form-group radio_buttons restaurants_food_category">
              <legend class="col-form-label pt-0">Food Category</legend>
              <button type="button" class="close" id="btn-close-position" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
              <input type="hidden" name="[food_category]" value="">
              <div class="wrapper">
                <% food_category.each do |input| %>
                  <div class="form-check">
                    <input class="form-check-input radio_buttons" type="radio" value="<%= input %>" name="[food_category]" id="_restaurants_food_category_<%= input %>">
                    <label class=" radio-buttons-food form-check-label collection_radio_buttons" for="_restaurants_food_category_<%= input %>"><%= input %></label>
                  </div>
                <% end %>
              </div>
            </fieldset>
            <fieldset class="form-group radio_buttons restaurants_rating">
              <legend class="col-form-label pt-0">Restaurant Rating</legend>
              <input type="hidden" name="[rating]" value="">
              <div class="rating-form">
                <% Restaurant::RATINGS.each do |input| %>
                  <div class="form-check">
                    <input class="form-check-input radio_buttons" type="radio" value="<%= input %>" name="[rating]" id="_restaurants_rating_<%= input %>">
                    <label class="form-check-label collection_radio_buttons" for="_restaurants_rating_<%= input %>"><i class="fas fa-star"></i>
                    </label>
                  </div>
                <% end %>
              </div>
            </fieldset>
            <fieldset class="form-group radio_buttons restaurants_price_level">
            <legend class="col-form-label pt-0">Price Range</legend>
            <input type="hidden" name="[price_level]" value="">
              <div class="price-form">
                <% Restaurant::PRICE_LEVEL.each do |input| %>
                  <div class="form-check">
                    <input class="form-check-input radio_buttons" type="radio" value="<%= input %>" name="[price_level]" id="_restaurants_price_level_<%= input %>">
                    <label class="form-check-label collection_radio_buttons" for="_restaurants_price_level_<%= input %>"><i class="fas fa-euro-sign"></i></label>
                  </div>
                <% end %>
              </div>
            </fieldset>
            <%= hidden_field_tag :event, @event.id %>
            <%= submit_tag 'Apply filters', class: "btn-lesconvives"%>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Card des restos

 <div class="cards">
    <%# @results_restaurants.each do |result|%>
      <%#= link_to restaurant_path(result, event: params[:event]) do %>

      <%# if result.photo.attached? %>
        <div class="card-trip mx-3">
          <div style="position: relative">
              <%#= cl_image_tag result.photo.key , alt: "photo restaurant", crop: :fill %>
             <a href="javascript: void(0)"><i class="fas fa-check-circle restaurant-select" data-selected-restaurant="<%#= result.id %>" data-selected-event="<%#= @event.id %>" style="position: absolute;"></i></a>
          </div>
          <div class="card-trip-infos">
            <div>
              <p> <%#= result.name %> </p>
              <%# if result.rating %>
                <p>
                  <%# result.rating.times do%>
                    <i class="fas fa-star"></i>
                  <%# end %>
                  <%# (5 - result.rating).times do %>
                    <i class="fas fa-star" id="level-missing"></i>
                  <%# end %>
                </p>
              <%# end %>
              <p> <%#= result.short_address %></p>
            </div>
            <h2 class="card-trip-pricing"><%#= ("€"*result.price_level.to_i) %></h2>
          </div>
        </div>
      <%# end %>
      <%# end %>
    <%# end %>
  </div>
<div>
    <%#= link_to "Back to Friends List", new_event_participant_path(@event), class: "btn btn-lesconvives", id:"loader"%>
</div>
-->

app/views/restaurants/show.html.erb
<div>
  <%= link_to restaurants_path(event: params[:event], anchor: "zoom") do%>
	  <i class="fas fa-chevron-left"></i>
	<% end %>
</div>

<div class="img-background" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= cl_image_path @restaurant.photo.key , alt: "photo restaurant" %>)"></div>

<!-- card description -->
  <ul class="list-group">
    <li class="list-group-item" id="title-resto">
      <%= @restaurant.name %>
      <div>
        <a href="javascript: void(0)"><i class="fas fa-check-circle restaurant-select" data-selected-restaurant="<%= @restaurant.id %>" data-selected-event="<%= @event.id %>" style="position: absolute;"></i></a>
      </div>
    </li>
    <li class="list-group-item">
      <i class="fas fa-map-marker-alt"></i>
      <%= @restaurant.short_address %>
    </li>
    <% if @restaurant.url %>
      <li class="list-group-item" class="restaurant-url">
        <i class="fas fa-globe"></i>
        <%= link_to @restaurant.url, "#{@restaurant.url}", :target =>"_blank" %>
      </li>
    <% end %>
    <% if @restaurant.opening_hours %>
      <li class="list-group-item">
        <p class="hourglass"><i class="fas fa-hourglass-start"></i> Opening Hours </p>
        <% array = JSON.parse(@restaurant.opening_hours) %>
        <% array.each do |hour| %>
          <p class="hours"><%= hour %></p>
        <% end %>
      </li>
    <% end %>

    <% if @restaurant.rating %>
      <li class="list-group-item">
        <% @restaurant.rating.times do%>
          <i class="fas fa-star"></i>
        <% end %>
        <% (5 - @restaurant.rating).times do %>
          <i class="fas fa-star" id="level-missing"></i>
        <% end %>
      </li>
    <% end %>

    <% if @restaurant.price_level %>
      <li class="list-group-item">
        <% @restaurant.price_level.to_i.times do %>
          <i class="fas fa-euro-sign"></i>
        <% end %>
        <% (5 - @restaurant.price_level.to_i).times do %>
          <i class="fas fa-euro-sign" id="level-missing"></i>
        <% end %>
      </li>
    <% end %>
    <% if @restaurant.food_category %>
      <li class="list-group-item">
      <i class="fas fa-utensils"></i> <%= @restaurant.food_category %></li>
    <% end %>
  </ul>

<div style="margin-top: 15px; display:flex; justify-content: center; text-align: center;">
    <%= link_to @restaurant.phone ? "tel:#{@restaurant.phone}" : @restaurant.url, class: "btn-lesconvives cta-call", target: @restaurant.phone ? "" : "_blank" do %>
      Make a Reservation  <i class="fas <%= @restaurant.phone ? "fa-phone" : "fa-globe" %>"></i>
    <% end %>
</div>