config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  devise_scope :user do
    authenticated  do
      root to: 'users#show'
    end

    unauthenticated do
      root to: 'pages#home', as: 'unauthenticated_root'
    end
  end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: [:show] do
    resources :addresses, only: %i[index new create edit update destroy] do
      post :create_from_coordinates, on: :collection
      patch :update_from_participants, on: :collection
    end
  end

  resources :events, only: %i[show new create] do
    resources :participants, only: %i[new create]
    resources :votes, only: %i[new create]
  end
  resources :participants, only: %i[destroy]
  resources :restaurants, only: %i[index show new create]
  resources :selected_restaurants, only: %i[create]

end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController

  def new
    @user = User.find(params[:user_id])
    @address = Address.new()
  end

  def create
    @address = Address.new(params_address)
    @address.user = User.find(params[:user_id])
    if @address.save
      if @address.active == true
        current_user.addresses.where.not(id: params[:id]).update_all(active: false)
      end
      redirect_to root_path
    else
      render :new
    end
  end

  def create_from_coordinates
    @address = Address.new(params_address)
    @address.user = current_user
    results = Geocoder.search([@address.latitude, @address.longitude])
    @address.full_address = results.first.address
    @address.name = "Other"
    @address.active = true
    if @address.save
      current_user.addresses.where.not(id: params[:id]).update_all(active: false)
    end
    redirect_to root_path
  end

  def index
    @new_address = Address.new()
    @addresses = current_user.addresses
    @user = current_user
  end

  def update
    @address = Address.find(params[:id])
    if @address.update(params_address)
      if @address.active == true
        current_user.addresses.where.not(id: params[:id]).update_all(active: false)
      end
      redirect_to root_path
    else
      render :new
    end
  end

  def update_from_participants
    @address = Address.find(params[:address])
    @user = User.find(params[:user_id])
    @participant = Participant.find(params[:participant])
    @event = Event.find(params[:event])
    @participant.update(address: @address)
    @address.update!(active: true)
    @user.addresses.where.not(id: params[:address]).update_all(active: false)
    redirect_to new_event_participant_path(@event)
  end

  def destroy
    @address = Address.find(params[:id])
    @address.destroy
    redirect_to user_addresses_path
  end

  private

  def params_address
    params.require(:address).permit(:name, :full_address, :active, :latitude, :longitude)
  end

end

app/views/addresses/index.html.erb
<%= render 'shared/navbar' %>
<div class="d-flex flex-column user-show", style="height: 100vh;">

  <div class="top-div d-flex flex-column justify-content-center align-items-center">

    <div class="d-flex">
      <h2> <%= "#{@user.first_name} addresses" %></h2>
    </div>

    <div class="container">
        <%= simple_form_for @new_address, url: create_from_coordinates_user_addresses_path(@user), html: { method: :post, id: "geolocation-form" } do |f| %>
          <%= f.input :latitude, as: :hidden %>
          <%= f.input :longitude, as: :hidden %>
          <%= f.submit "My current position", class: "btn btn-success", id: "my-position" %>
        <% end %>
    </div>
    <div class="container">
      <%= link_to "Add a new address manually", new_user_address_path(@user), class: "btn btn-secondary mt-3" %>
    </div>
  </div>

  <div class="bottom-div addresses">
    <% @addresses.each_with_index do |address, index| %>
      <div class="container">
        <div class="container d-flex justify-content-between p-3">
          <h4> <%= "Address ##{index + 1}" %></h4>
          <div>
            <%= link_to user_address_path(@user, address.id), method: :delete, remote: true do %>
              <i class="fas fa-trash"></i>
            <% end %>
          </div>
        </div>
        <div>
          <%= simple_form_for address, url: user_address_path(@user, address.id), html: { method: :patch }, remote: true do |f| %>
            <%= f.input :full_address, label: false %>
            <%= f.input  :name, collection: ["Home", "Work", "Other"] %>
            <div class="container ml-2">
              <%= f.input :active, label: "Default address", as: :boolean %>
            </div>
            <%= f.submit class: "btn btn-success" %>
          <% end %> 
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/addresses/new.html.erb
<div class="d-flex flex-column user-show", style="height: 100vh;">

  <div class="top-div d-flex flex-column justify-content-center align-items-center">

    <div class="d-flex">
      <h2> <%= "#{@user.first_name}, add an address !" %></h2>
    </div>

    <div class="container">
        <%= simple_form_for @address, url: create_from_coordinates_user_addresses_path(@user), html: { method: :post, id: "geolocation-form" } do |f| %>
          <%= f.input :latitude, as: :hidden %>
          <%= f.input :longitude, as: :hidden %>
          <%= f.submit "My current position", class: "btn btn-success", id: "my-position" %>
        <% end %>
    </div>
  </div>

  <div class="bottom-div addresses">
    <div class="container p-3">
      <h4>Enter an address manualy</h4>
      <%= simple_form_for @address, url: user_addresses_path(@user), html: { method: :post } do |f| %>
        <%= f.input :full_address %>
        <%= f.input  :name, collection: ["Home", "Work", "Other"] %>
        <div class="container ml-2">
          <%= f.input :active, label: "Default address", as: :boolean %>
        </div>
        <%= f.submit class: "btn btn-light" %>
      <% end %>
    </div>
  </div>

</div>